const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const json=(b,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"Content-Type":"application/json",...cors}});
const clean=x=>typeof x==="string"?x.trim():null;
const validId=x=>typeof x==="string"&&/^P\d{6}$/.test(x);
const auth=(req,env)=>(req.headers.get("Authorization")||"")==="Bearer "+env.ADMIN_PASSWORD;
async function gh(env,path,opt={}){const r=await fetch("https://api.github.com"+path,{...opt,headers:{"Accept":"application/vnd.github+json","Authorization":"Bearer "+env.GITHUB_TOKEN,"X-GitHub-Api-Version":"2026-03-10","Content-Type":"application/json",...(opt.headers||{})}});const t=await r.text();let b={};try{b=JSON.parse(t)}catch{}if(!r.ok)throw Error(b.message||("GitHub "+r.status));return b}
async function getGraph(env){const x=await gh(env,"/repos/"+env.GITHUB_OWNER+"/"+env.GITHUB_REPO+"/contents/"+env.GITHUB_PATH+"?ref="+env.GITHUB_BRANCH);const raw=atob((x.content||"").replace(/\n/g,""));const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));return {data:JSON.parse(new TextDecoder().decode(bytes)),sha:x.sha}}
function b64(s){const bytes=new TextEncoder().encode(s);let o="";for(let i=0;i<bytes.length;i+=32768)o+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(o)}
const nextId=d=>"P"+String(Math.max(0,...d.persons.map(p=>Number(String(p.id).slice(1))||0))+1).padStart(6,"0");
function applyOne(d,p){const x=p.payload||{},person=id=>d.persons.find(q=>q.id===id);
if(p.operation==="ADD_PERSON"){const display=clean(x.displayName)||[x.firstName,x.middleName,x.familyName].filter(Boolean).join(" ");if(!display)throw Error("Name is required");const id=x.id||nextId(d);if(!validId(id)||person(id))throw Error("Person ID conflict. Reload and submit again.");d.persons.push({id,firstName:clean(x.firstName)||display,middleName:clean(x.middleName),familyName:clean(x.familyName),displayName:display,nickname:clean(x.nickname),maidenName:clean(x.maidenName),gender:clean(x.gender),dateOfBirth:clean(x.dateOfBirth),dateOfDeath:clean(x.dateOfDeath),lifeStatus:x.dateOfDeath?"deceased":clean(x.lifeStatus)||"unknown",birthPlace:clean(x.birthPlace),birthRegion:clean(x.birthRegion),birthCountry:clean(x.birthCountry),deathPlace:clean(x.deathPlace),currentLocation:clean(x.currentLocation),occupation:clean(x.occupation)||"",notes:clean(x.notes)||"",maritalStatus:clean(x.maritalStatus)||"unknown",isMarried:Boolean(x.isMarried),recordStatus:"active"});
 }else if(p.operation==="UPDATE_PERSON"){if(!validId(x.personId)||!person(x.personId)||person(x.personId).recordStatus==="deleted")throw Error("Unknown or archived person ID");const q=person(x.personId);for(const k of ["firstName","middleName","familyName","displayName","nickname","maidenName","gender","dateOfBirth","dateOfDeath","birthPlace","birthRegion","birthCountry","deathPlace","currentLocation","occupation","notes","maritalStatus"])if(k in x)q[k]=clean(x[k]);if(q.dateOfDeath&&q.dateOfBirth&&q.dateOfDeath<q.dateOfBirth)throw Error("Death date cannot precede birth date");q.lifeStatus=q.dateOfDeath?"deceased":clean(x.lifeStatus)||q.lifeStatus||"unknown";if("isMarried" in x)q.isMarried=Boolean(x.isMarried);
 }else if(p.operation==="DELETE_PERSON"){if(!validId(x.personId)||!person(x.personId))throw Error("Unknown person ID");const q=person(x.personId);q.recordStatus="deleted";q.archivedAt=new Date().toISOString();q.archiveReason=clean(x.reason)||"Approved archive";
 }else if(p.operation==="ADD_PARENT_CHILD"){if(!validId(x.parentId)||!validId(x.childId)||x.parentId===x.childId||!person(x.parentId)||!person(x.childId))throw Error("Invalid parent/child IDs");if(d.relationships.parentChild.some(r=>r.parentId===x.parentId&&r.childId===x.childId))throw Error("Relationship already exists");d.relationships.parentChild.push({parentId:x.parentId,childId:x.childId,role:clean(x.role)||"parent",order:Number(x.order)||1});
 }else if(p.operation==="ADD_SPOUSE"){if(!validId(x.personAId)||!validId(x.personBId)||x.personAId===x.personBId||!person(x.personAId)||!person(x.personBId))throw Error("Invalid spouse IDs");if(d.relationships.spouses.some(r=>new Set([r.personAId,r.personBId]).size===2&&[r.personAId,r.personBId].includes(x.personAId)&&[r.personAId,r.personBId].includes(x.personBId)))throw Error("Relationship already exists");d.relationships.spouses.push({personAId:x.personAId,personBId:x.personBId,order:Number(x.order)||1,marriageDate:clean(x.marriageDate),marriagePlace:clean(x.marriagePlace),status:clean(x.status)||"married",divorceDate:clean(x.divorceDate)});
 }else throw Error("Unsupported operation: "+p.operation)}
function applyProposal(d,p){if(p.operation==="BATCH_UPDATE"){const q=p.payload||{};if(q.baseLastUpdated&&q.baseLastUpdated!==d.lastUpdated)throw Error("Stale request: reload and submit again.");const list=Array.isArray(q.changes)?q.changes:[];if(!list.length)throw Error("Batch contains no changes");for(const c of list){if(!c?.type)throw Error("Invalid batch change");applyOne(d,{operation:c.type,payload:c.payload||{}})}}else applyOne(d,p);d.lastUpdated=new Date().toISOString()}
async function commitGraph(env,data,sha,message){return gh(env,"/repos/"+env.GITHUB_OWNER+"/"+env.GITHUB_REPO+"/contents/"+env.GITHUB_PATH",{method:"PUT",body:JSON.stringify({message,content:b64(JSON.stringify(data,null,2)+"\n"),sha,branch:env.GITHUB_BRANCH})})}
export default{async fetch(req,env){if(req.method==="OPTIONS")return new Response(null,{headers:cors});const url=new URL(req.url);try{
if(url.pathname==="/health")return json({ok:true,service:"family-graph-request-api"});
if(url.pathname==="/requests"&&req.method==="POST"){const b=await req.json(),p=b?.proposal;if(!p||p.operation!=="BATCH_UPDATE")return json({error:"Only BATCH_UPDATE requests are accepted."},400);const id=crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare("INSERT INTO requests(id,status,title,proposal_json,source,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").bind(id,"pending","Family graph batch update",JSON.stringify(p),clean(b.source)||"public-web",now,now).run();return json({ok:true,id,status:"pending",createdAt:now},201)}
if(url.pathname==="/requests"&&req.method==="GET"){if(!auth(req,env))return json({error:"Unauthorized"},401);const st=url.searchParams.get("status")||"pending";const rows=await env.DB.prepare("SELECT id,status,title,proposal_json,source,created_at,updated_at,note FROM requests WHERE status=? ORDER BY created_at ASC LIMIT 100").bind(st).all();return json({requests:(rows.results||[]).map(r=>({...r,proposal:JSON.parse(r.proposal_json)}))})}
const m=url.pathname.match(/^\/requests\/([^/]+)\/(approve|reject)$/);if(m&&req.method==="POST"){if(!auth(req,env))return json({error:"Unauthorized"},401);const id=decodeURIComponent(m[1]),action=m[2],b=await req.json(),row=await env.DB.prepare("SELECT * FROM requests WHERE id=?").bind(id).first();if(!row)return json({error:"Request not found"},404);if(row.status!=="pending")return json({error:"Request is already "+row.status},409);const note=clean(b.note)||"";if(action==="reject"){await env.DB.prepare("UPDATE requests SET status='rejected',note=?,updated_at=? WHERE id=?").bind(note,new Date().toISOString(),id).run();return json({ok:true,status:"rejected"})}const proposal=b.proposal||JSON.parse(row.proposal_json),g=await getGraph(env);applyProposal(g.data,proposal);await commitGraph(env,g.data,g.sha,"Apply approved family graph request "+id);await env.DB.prepare("UPDATE requests SET status='approved',note=?,proposal_json=?,updated_at=? WHERE id=?").bind(note,JSON.stringify(proposal),new Date().toISOString(),id).run();return json({ok:true,status:"approved",id})}
return json({error:"Not found"},404)}catch(e){return json({error:e.message||String(e)},500)}}};