name = "family-tree-community"
main = "worker.js"
compatibility_date = "2026-09-19"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "family-tree-community-db"
database_id = "f8872a81-b195-4436-b914-89c3b1096f82"

[vars]
GITHUB_OWNER = "shubhamturai"
GITHUB_REPO = "family-tree-community"
GITHUB_PATH = "data/family.json"
GITHUB_BRANCH = "main"

[assets]
directory = "./public"
binding = "ASSETS"

run_worker_first = true
